kind: pipeline
name: default

steps:
  - name: pre-build
    image: composer
    commands:
      - composer install
  - name: test
    image: composer
    commands:
      - composer test
  - name: lint
    image: composer
    commands:
      - composer lint-php
