kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: plugins/git
  settings:
    depth: 10
    skip_verify: true
- name: pre-build
  image: composer
  commands:
  - composer install
- name: test
  image: composer
  commands:
  - ./vendor/bin/robo test
- name: test-style
  image: composer
  commands:
  - ./vendor/bin/robo test:cs
